version: 2

jobs:
  init:
    docker:
      - image: alpine
    steps:
      - run: apk add --no-cache git curl openssh
      - checkout
      - run: ./.circleci/update-dockerhub-credentials.sh

  build-app-image:
    docker:
    - image: docker
    steps:
      - run: apk add --no-cache bash make git openssh
      - checkout
      - run: wget -O /vault.zip https://releases.hashicorp.com/vault/1.1.0/vault_1.1.0_linux_amd64.zip; unzip /vault.zip -d /usr/bin/
      - setup_remote_docker
      - run: make build-app-image
      - run: make publish-app-image

  build-cd-image:
    docker:
    - image: docker
    steps:
      - run: apk add --no-cache bash make git openssh
      - checkout
      - run: wget -O /vault.zip https://releases.hashicorp.com/vault/1.1.0/vault_1.1.0_linux_amd64.zip; unzip /vault.zip -d /usr/bin/
      - setup_remote_docker
      - run:
          name: Check if image build is required
          command: |
            make docker-login
            if [ -z "$(git show --name-only | grep build/docker)" ]; then
              DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect opuscapita/buhtig-s8k:cd && \
                circleci step halt || echo "Image doesn't exist, proceed"
            fi
      - run: make build-cd-image && make publish-cd-image

  deploy:
    docker:
    - image: opuscapita/buhtig-s8k:cd
      auth:
        username: ${DOCKERHUB_USER}
        password: ${DOCKERHUB_PASSWORD}
    working_directory: ~/build
    steps:
      - checkout
      - run: make aks-login
      - run: make deploy

workflows:
  version: 2
  commit:
    jobs:
      - init
      - build-app-image:
          requires:
            - init
      - build-cd-image:
          requires:
            - init
      - deploy:
          requires:
            - build-app-image
            - build-cd-image
